### ISSUE TITLE
Issue with "Getting Started Guide" in @site/docs/howtos/integrations/getting-started-guide.md

### ISSUE THREAD

**Issue by csestito** [demisto/content-docs#50] opened 2020-03-03 00:13 UTC
## Describe the problem

Links lead nowhere, due to use of quotations.

## Screenshots
![URL](https://i.imgur.com/xgVOKfS.png)

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

## Suggested fix
Remove quotations from the URLs

**Comment by fvigo** [comment] 2020-03-20 18:26
@csestito  which link exactly? cannot reproduce

**Comment by fvigo** [comment] 2020-03-20 18:42
Found it and fixed in #62 , thanks

**Closed** 2020-03-23 08:21 UTC
Labels: documentation
