### ISSUE TITLE
Issue with "GetListRow" in @site/docs/reference/scripts/get-list-row.md

### ISSUE THREAD

**Issue by neonizer70** [demisto/content-docs#1347] opened 2023-06-12 14:42 UTC
## Describe the problem

* Page: [GetListRow](https://xsoar.pan.dev/docs/reference/scripts/get-list-row)
* Source: https://github.com/demisto/content/blob/master//Packs/CommonScripts/Scripts/GetlistRow/README.md

Issue using get-list-row two get multiple values from a single row. have a list with the name of CS-FW-Level. The list contains two headers CSFWhostname,CSFWlevel. I can get the value of the first header CSFWhostname the second gets null as header is not found CSFWlevel has a space after it. The code below fixed the issue

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

## Suggested fix

 and strip to the following def list_to_headers_and_lines(list_data, list_separator: str):
    lines_and_headers = [line.strip().split(list_separator) for line in list_data.split('\n')]
    headers = lines_and_headers[0]
    return headers, lines_and_headers[1:]

**Comment by maimorag** [comment] 2023-08-22 09:16
Hey @neonizer70,
I couldn't reproduce the issue,
Also, from looking at the code it doesn't seem like a trailing space should affect the results that way.
Can you attach logs of execution before the fix where it failed for you using the debug-mode=true argument in the playground CLI?
Thanks in advance!

**Comment by maimorag** [comment] 2023-08-23 06:46
[link to the Jira issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-27384)

**Comment by maimorag** [comment] 2023-09-04 11:47
I have not received a response from you in the last two weeks, so I'm closing the bug.
Thanks again.

**Closed by maimorag** 2023-09-04 11:47 UTC
