### ISSUE TITLE
Issue with "System Diagnostics and Health Check" in @site/docs/reference/articles/system-diagnostics-and-health-check.md

### ISSUE THREAD

**Issue by PrasiddhaNP** [demisto/content-docs#1375] opened 2023-07-26 05:21 UTC
## Describe the problem

I am obesrving a permission issue when using this playbook. The scripts are  not running in the incident layout dynamic section. Its saying the "demisto-api-post" command is not availabe. This is a harmfull command and some permission or role is causing the issue 
Kindly let me know if there is any fix to it.

**Comment by ShahafBenYakir** [comment] 2023-08-15 10:59
Hi, this sounds like you are experiencing issues and not having documentation issues. This could be caused by different reasons including the users running it or other reasons. Since this is not the right place to discuss playbook tickets I am closing this ticket, please work with the XSOAR support on opening an official XSOAR support ticket.

**Closed by ShahafBenYakir** 2023-08-15 10:59 UTC
