### ISSUE TITLE
Issue with "XSOAR CI/CD" in @site/docs/reference/packs/content-management.md

### ISSUE THREAD

**Issue by PASteve** [demisto/content-docs#1383] opened 2023-08-14 15:26 UTC
## Describe the problem
 None of the embedded videos seem to play anymore.  I'm using the current version of Chrome on Windows.
 
 
* Page: [XSOAR CI/CD](https://xsoar.pan.dev/docs/reference/packs/content-management)
* Source: https://github.com/demisto/content-docs/blob/master/content-repo/extra-docs/packs/content-management.md

## Screenshots

![image](https://github.com/demisto/content-docs/assets/90780589/aaa9a59e-280b-46f9-bb28-fd57ace71c7a)

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

**Comment by Shellyber** [comment] 2023-08-15 08:58
All the videos on this page seem to work fine. I'm also using the latest Chrome version. 
![image](https://github.com/demisto/content-docs/assets/45915502/4fb6e607-c158-42e2-8215-9f70ff1e23f8)

Please try to refresh the page.
Closing this issue since it is not reproducible.
Please reopen if it still happens.

**Closed by Shellyber** 2023-08-15 08:58 UTC
