### ISSUE TITLE
Issue with "PAN-OS Policy Optimizer" in @site/docs/reference/packs/policy-optimizer.md

### ISSUE THREAD

**Issue by leocf8585** [demisto/content-docs#1202] opened 2022-10-04 16:23 UTC
## Describe the problem

Can not login the panorama instance using the latest policy optmizer 1.0.8 

2022-10-04T11:31:00.028273716-04:00 debug: (PAN-OS Policy Optimizer_instance_117e3fd95-a7a3-49fd-87de-48ac3e9f10f8_PAN-OS Policy Optimizer_test-module) 
Traceback (most recent call last):
  File "<PAN-OS Policy Optimizer>", line 429, in main
  File "<PAN-OS Policy Optimizer>", line 67, in login
ValueError: invalid literal for int() with base 10: ''

Entry
Executed on 2022-10-04T11:31:00.029010626-04:00

Raw Response section:
invalid literal for int() with base 10: ''.
 Trace:Traceback (most recent call last):
  File "<string>", line 12025, in main
  File "<string>", line 11663, in login
ValueError: invalid literal for int() with base 10: ''

Traceback (most recent call last):
  File "<PAN-OS Policy Optimizer>", line 429, in main
  File "<PAN-OS Policy Optimizer>", line 67, in login
ValueError: invalid literal for int() with base 10: ''

## Screenshots
Error Attached.

## Environment
 - OS: [e.g. Windows] Linux
 - Browser: [e.g. chrome, safari, firefox..] Firefox
 - Browser Version:

## Suggested fix

![policy_optmizer](https://user-images.githubusercontent.com/48316132/193872908-70e0c2b3-63e7-482c-b93c-94056a3348b9.jpg)

**Comment by MosheEichler** [comment] 2022-10-06 08:01
Hi @leocf8585 I close this issue since the issue is not related to the docs.
Please open [support ticket](https://support.paloaltonetworks.com/Support/Index).

**Closed by MosheEichler** 2022-10-06 08:01 UTC
